[tox]
envlist =
    {py310,py311,py312,py313,py314}-{django42,django51,django52}
    {py314}-{django60}

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14

deps =
    pytest>=7.0
    pytest-django>=4.5
    coverage
    django42: django>=4.2,<5.0
    django51: django>=5.1,<5.2
    django52: django>=5.2,<6.0
    django60: django>=6.0,<6.1

commands = pytest {posargs}
