[tox]
envlist =
    {py310,py311,py312}-{django42,django51,django52}
    {py312}-{django60,django61}

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12

deps =
    pytest>=7.0
    pytest-django>=4.5
    coverage
    django42: django>=4.2,<5.0
    django51: django>=5.1,<5.2
    django52: django>=5.2,<6.0
    django60: django>=6.0,<6.1
    django61: django>=6.1,<6.2

commands = pytest {posargs}
